config/routes.rb
Compliments::Application.routes.draw do
  resources :messages

  resources :users do
    resources :messages
  end
  
  match 'users/search'=>'users#search'
  

  root :to => 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  validate :is_valid_compliment, :on=>:create
  attr_accessible :body, :user_id
  belongs_to :user
  
  def is_valid_compliment
    if(body.empty?)
      errors.add(:body, "Body cannot be empty")
      false
    else
      if(user_id==nil)
        errors.add(:user_id, "Message must have a recipient")  
        false
      end
      if(JSON.parse(Sentimentalizer.analyze(body))['sentiment']==':(')
        errors.add(:body, "Your message is not a compliment. Try being nice :)")
        false
      end
    end
  end
end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  default :from => "complimentsapp@gmail.com"

  # send a signup email to the user, pass in the user object that contains the user's email address
  def signup_email(user)
    mail( 
    :to => user.email,
    :subject => "Thanks for creating an account. Check it out "+link_to("here", user_url(@user))
    )
  end
  def notif_email(user, message)
    mail( 
    :to => user.email,
    :subject => "You received an anonymous compliment!",
    :body=>"Check it out "+ActionController::Base.helpers.link_to("here", message_url(message))
    )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :id, :email, :credits
  validates :email, :presence=>true
  has_many :messages
  before_save :default_values
  def default_values
    self.credits ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    if(params[:user_id]!=nil)
      @user=User.find(params[:user_id])
      @messages=@user.messages
    else
      @messages=Message.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new
    if(session[:user_id]!=nil)
      @user=User.find(session[:user_id])
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    if(User.find_by_email(params[:email])!=nil)
      params[:message][:user_id]=User.find_by_email(params[:email]).id
    else
      params[:message][:user_id]=User.create(:email=>params[:email]).id
    end
    @message = Message.new(params[:message])
    

    respond_to do |format|
      if @message.save
        if(session[:user_id]!=nil)
          User.find(session[:user_id]).credits+=1
        end
        Notifier.notif_email(@message.user, @message).deliver
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @credits= @user.credits
    @messages = @user.messages.limit((@credits/2).floor)
    @hidden=@user.messages.count-@messages.count
    if(@messages.count==0)
      if(@credits==0)
        @reason="You don't have enough credits to see any messages"
      else
        @reason="You have no compliments"
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    Notifier.signup_email(@user).deliver
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find_by_email(params[:email])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  def search
    @user=User.find_by_email(params[:email])
    session[:user_id]=@user.id
    respond_to do |format|
      format.html {redirect_to @user, notice: "Found you!"}
      format.json { render json: @user}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Compliments</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" href="/css/bootstrap.css"></link>
   <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Compliments App</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Home", root_path %></li>
            </ul>
            <form class="navbar-search pull-right" action="/users/search" method="post">
			  <input type="text" class="search-query input-large" name="email" placeholder="Find your compliments by email">
			</form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class="container-fluid">
	<%= yield %>
</div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-horizontal">
  	<div class="control-group">
    <%= f.label :body, :class=>"control-label" %>
	    <div class="controls">
		    <%= f.text_field :body %>
	    </div>
    </div>
    <div class="control-group">
    <%= f.label "Recipient", :class=>"control-label" %>
	    <div class="controls">
		   <input type="text" name="email"></input>
	    </div>
    </div>
	  <div class="control-group">
	  	<div class="controls">
	    	<%= f.submit :class=>"btn btn-primary" %>
	  	</div>
	  </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Body</th>
      <th>Recipient</th>
    </tr>
  </thead>
  <tbody>
  	<% @messages.each do |message| %>
    <tr>
      <td><%= link_to message.body, message %></td>
	  <td><%= link_to message.user.email, message.user %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Message', new_message_path, :class=>'btn btn-success' %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @message.body %>
</p>

<p>
  <b>Recipient:</b>
  <%= @message.user.email %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'See messages', user_messages_path(user) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p id="reason"><%= @reason %></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
  	<% @messages.each do |message| %>
    <tr>
      <td><%= link_to message.body, message %></td>
    </tr>
    <% end %>
    <tr>
    	<td>
    		<%= @hidden %> hidden compliments. Give someone else 2 compliments to see another one of yours
    	</td>
	</tr>
  </tbody>
</table>

<br />

<%= link_to 'New Message', new_message_path, :class=>'btn btn-success' %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>